##############################################################
#                                                            #
#                                                            #
#                     Coded by Happy X Katara!                       #
#                                                            #
#                                                            #
##############################################################


messages:
  successfullyMessage: "&aᴋᴀᴨчᴀ уᴄᴨᴇɯно ᴨᴩойдᴇнᴀ. ᴨᴩияᴛной иᴦᴩы!" # Текст при успешном прохождении капчи
  kickMessage: "&cʙы нᴇ ᴨᴩоɯᴧи ᴋᴀᴨчу!" # Текст при неверном прохождении капчи

# Плэйсхолдер %number% - ответ чтобы пройти капчу
# Плэйсхолдер %timeLeft% - оставшееся время для ответа

bossBarName: " &f(оᴄᴛᴀᴧоᴄь %timeLeft% ᴄᴇᴋунд)"
anvilName: "&7ʙʙᴇдиᴛᴇ чиᴄᴧо %number%" # Название меню капчи
time: 60 # Время на решение капчи
notification: # Оповещение об успешном прохождении капчи

  sound: true # Звук при оповещении игрока
  soundType: "ENTITY_EXPERIENCE_ORB_PICKUP" # Тип звука при оповещении

  message: true # В виде сообщения в чат
  title: false # В виде сообщения на весь экран